export type WajibPajakBadanUsaha = {
  kodeWPBadan: string;
  namaBadan: string;
  email: string;
  npwp?: string;
  namaNpwp?: string;
  kotaNpwp?: string;
  bankTransfer?: string;
  noRekening?: string;
  namaRekening?: string;
  namaNaraHubung: string;
  kontakNaraHubung: string;
  adaSkbPPh23: boolean;
  masaBerlakuBebasPPh23?: Date;
  fileFotoIdentitasBadan: string;
  fileFotoBuktiRekening: string;
  fileFotoNpwp?: string;
  fileSuratBebasPPh23?: string;
  statusPkp: string;
};
